# This workflow builds and publishes a Docker image to the GitHub Container Registry and Docker Hub.
#
# It is triggered on the following events:
# - A push to the "main" branch, which builds and pushes the image with the 'latest' tag.
# - The creation of a new release, which builds and pushes the image with the release version as the tag.
# - A pull request to the "main" branch, which builds the image but does not push it.

name: Publish Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Required for signing the images with cosign.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/obeone/session-webhook
            docker.io/obeoneorg/session-webhook
          tags: |
            # Set 'latest' tag for the default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Set version tag for releases
            type=ref,event=tag

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/arm64
            linux/amd64

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3

      - name: Sign container images
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes "ghcr.io/obeone/session-webhook@${{ steps.docker_build.outputs.digest }}"
          cosign sign --yes "docker.io/obeoneorg/session-webhook@${{ steps.docker_build.outputs.digest }}"

      - name: Update Docker Hub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: obeoneorg/session-webhook
